server:
  port: 3700

#  h2 data source
spring:
  datasource:
    url: jdbc:h2:mem:spring-cloud
    username: spring-cloud
    driver-class-name: org.h2.Driver
  application:
    name: payment-service

  h2:
    console:
      enabled: true


#eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
# application
